<?xml version="1.0" encoding="utf-8"?><Database Name="MyDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\MyDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MyDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="U_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="User_type" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Association Name="User_Order" Member="Orders" ThisKey="U_ID" OtherKey="U_ID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="U_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="P_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QTY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Order" Member="User" ThisKey="U_ID" OtherKey="U_ID" Type="User" IsForeignKey="true" />
      <Association Name="Product_Order" Member="Product" ThisKey="U_ID" OtherKey="P_ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="P_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="P_Name" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="P_Description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="P_Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="P_Category" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="P_Image" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="P_Status" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Product_Order" Member="Orders" ThisKey="P_ID" OtherKey="U_ID" Type="Order" />
    </Type>
  </Table>
</Database>